name: 👩🏼‍💻 Azure App Service request
description: This form is used to create Azure infrastructure
title: "👩🏼‍💻☁️ Create an Azure App Service"
labels: ["issueops:web"]
projects: ["returngis/7"]
assignees:
  - teams/devs
  - 0gis0
body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening an issue to create an Azure Web App". Please fill out the sections below.
  - type: input
    id: web_name
    attributes:
      label: Web Name
      description: "Please enter the name of the Azure Web App"
    validations:
      required: true
  - type: input
    id: resource_group_name
    attributes:
      label: Resource Group
      description: "Please enter the name of the Azure Resource Group"
    validations:
      required: true
  - type: dropdown
    id: region
    attributes:
      label: Region
      multiple: false
      options:
        - spaincentral
        - francecentral
        - westeurope
        - northeurope
      default: 0
